# Generated by Django 5.0.6 on 2024-05-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='driveapp.order'),
        ),
    ]
