# Generated by Django 5.0.6 on 2024-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0003_alter_list_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='list',
            name='product',
        ),
        migrations.AddField(
            model_name='list',
            name='product',
            field=models.ManyToManyField(to='driveapp.product'),
        ),
    ]
