# Generated by Django 5.0.6 on 2024-05-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0005_remove_list_product_remove_list_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='products',
        ),
        migrations.AddField(
            model_name='list',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='driveapp.product'),
        ),
        migrations.AddField(
            model_name='list',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='driveapp.List', to='driveapp.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparation', 'Preparation'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ListProduct',
        ),
    ]
