# Generated by Django 5.0.6 on 2024-05-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0006_remove_list_products_list_product_list_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driveapp.product'),
        ),
    ]
