# Generated by Django 5.0.6 on 2024-05-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0007_alter_list_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='customer',
        ),
    ]
