# Generated by Django 5.0.6 on 2024-05-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0008_rename_client_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
