# Generated by Django 5.0.6 on 2024-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0010_alter_product_date_peremption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
