# Generated by Django 5.0.6 on 2024-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0013_alter_product_brand_alter_product_date_peremption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
