# Generated by Django 5.0.6 on 2024-05-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0014_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='forname',
            new_name='forename',
        ),
    ]
